axf1/app1/urls.py
from django.conf.urls import url
from app1 import views

urlpatterns = [
    # 首页
    url(r'^home/', views.home, name='home'),
    # 购物车
    url(r'^cart/', views.cart, name='cart'),
    # 闪购超市
    url(r'^market/$', views.market, name='market'),
    url(r'^market/(\d+)/(\d+)/(\d+)', views.use_market, name='use_market'),
    # 个人中心
    url(r'^mine/', views.mine, name='mine'),

    # 添加购物车
    url(r'^addCart/', views.add_cart, name='addCart'),
    url(r'^subCart/', views.sub_cart, name='subCart'),

    # 修改购物车中商品的选择情况
    url(r'^changeSelectStatus/', views.change_select_status, name='change'),

    # 下单
    url(r'^g_order/', views.g_order, name='g_order'),

    # 修改名单状态
    url(r'^changeOrderStatus/', views.change_order_status, name='change_order_status'),

    # 待付款订单
    url(r'^waitPay/', views.order_wait_pay, name='order_wait_pay'),

    # 付款页面
    url(r'^payMygoods/', views.pay_my_goods, name='pay_my_goods'),

    # 待收货
    url(r'^payed/', views.order_payed, name='order_payed'),

    # 总价
    url(r'^allPrice/', views.all_price, name='all_price'),

    # 全选
    url(r'^changeAll/', views.change_all, name='change_all')

]

axf1/axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.views.static import serve

from app1 import views
from axf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app1/', include('app1.urls', namespace='app1')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^$', views.home),
    # 部署时用到的路由
    url(r'^static(?P<path>.*)$', serve, {"document_root": settings.STATICFILES_DIRS[0]}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

axf1/app1/models.py
from django.db import models

from user.models import UserModel


class Main(models.Model):

    # 图片字段
    img = models.CharField(max_length=200)
    # 名称字段
    name = models.CharField(max_length=100)
    # 通用id
    trackid = models.CharField(max_length=16)

    class Meta:
        abstract = True


class MainWheel(Main):

    # 轮播banner
    class Meta:
        db_table = 'axf_wheel'


class MainNav(Main):

    # 导航
    class Meta:
        db_table = 'axf_nav'


class MainMustBuy(Main):

    # 必购
    class Meta:
        db_table = 'axf_mustbuy'


class MainShop(Main):

    # 商店
    class Meta:
        db_table = 'axf_shop'


# 主要展示的商品
class MainShow(Main):

    categoryid = models.CharField(max_length=16)
    # 分类名称
    brandname = models.CharField(max_length=100)

    img1 = models.CharField(max_length=200)
    childcid1 = models.CharField(max_length=16)
    productid1 = models.CharField(max_length=16)
    # 商品名称
    longname1 = models.CharField(max_length=100)
    # 原价格
    price1 = models.FloatField(default=0)
    # 折后价格
    marketprice1 = models.FloatField(default=1)

    img2 = models.CharField(max_length=200)
    childcid2 = models.CharField(max_length=16)
    productid2 = models.CharField(max_length=16)
    # 商品名称
    longname2 = models.CharField(max_length=100)
    # 原价格
    price2 = models.FloatField(default=0)
    # 折后价格
    marketprice2 = models.FloatField(default=1)

    img3 = models.CharField(max_length=200)
    childcid3 = models.CharField(max_length=16)
    productid3 = models.CharField(max_length=16)
    # 商品名称
    longname3 = models.CharField(max_length=100)
    # 原价格
    price3 = models.FloatField(default=0)
    # 折后价格
    marketprice3 = models.FloatField(default=1)

    class Meta:
        db_table = 'axf_mainshow'


class FoodType(models.Model):
    # 分类id
    typeid = models.CharField(max_length=16)
    # 商品分类名
    typename = models.CharField(max_length=100)
    # 商品的子分类名
    childtypenames = models.CharField(max_length=200)
    # 排序
    typesort = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_foodtypes'


class Goods(models.Model):
    # 商品的id
    productid = models.CharField(max_length=16)
    # 商品的图片
    productimg = models.CharField(max_length=200)
    # 商品的名称
    productname = models.CharField(max_length=100)
    # 商品的规格名
    productlongname = models.CharField(max_length=200)
    isxf = models.IntegerField(default=1)
    pmdesc = models.CharField(max_length=200)
    # 规格
    specifics = models.CharField(max_length=100)
    # 折后价格
    price = models.FloatField(default=1)
    # 原价格
    marketprice = models.FloatField(default=1)
    # 分类id
    categoryid = models.CharField(max_length=16)
    # 子分类id
    childcid = models.CharField(max_length=16)
    # 名称
    childcidname = models.CharField(max_length=100)
    dealerid = models.CharField(max_length=16)
    # 排序
    storenums = models.IntegerField(default=1)
    # 销量排序
    productnum = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_goods'


class CartModel(models.Model):

    # 关联用户
    user = models.ForeignKey(UserModel)
    # 关联商品
    goods = models.ForeignKey(Goods)
    # 商品的个数
    c_num = models.IntegerField(default=1)
    # 商品是否被选择
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'axf_cart'


class OrderModel(models.Model):
    # 关联用户
    user = models.ForeignKey(UserModel)
    # 数量
    o_num = models.CharField(max_length=64)
    # 0代表已下单, 但是未付款, 1 已付款未发货 2 已付款, 已发货
    o_status = models.IntegerField(default=0)
    o_create = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'axf_order'


class OrderGoodsModel(models.Model):
    # 关联的商品
    goods = models.ForeignKey(Goods)
    # 关联的订单
    order = models.ForeignKey(OrderModel)
    # 商品的个数
    goods_num = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_order_goods'

axf1/templates/order/order_info.html
{% extends 'base.html' %}
{% load static %}

{% block EXTJS %}
{#    <script type="text/javascript" src="{% static 'app/order/js/order.js' %}"></script>#}
    <script type="text/javascript" src="{% static 'app/common/function.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="order_info" class="container">

    <!--订单编号-->
    <h3>订单编号: {{ order.o_num }}</h3>
    <!--处理结束-->
    <ul>
        {% for ordergoods in order.ordergoodsmodel_set.all %}
        <!--所有订单信息展示-->
            <li>
                <!--商品名称展示-->
                {{ ordergoods.goods.productname }}
                <img src="{{ ordergoods.goods.productimg }}">

                <span> <!-- 数量展示 -->{{ ordergoods.goods_num }}</span>
            </li>

        <!--订单处理结束-->
        {% endfor %}

    </ul>
        {% csrf_token %}
        <!--订单id展示-->
        <button onclick="change_order({{ order.id }})" class="btn btn-success btn-block">
            Alipay
        </button>

    </div>


{% endblock %}

axf1/templates/order/order_list_payed.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待收货订单列表</h3>
    <ul>
    {% for order in orders %}
        <!--订单展示-->
            <li>
                <a href="#">
                    <p><!-- 订单id -->订单编号: {{ order.o_num }}</p>
                    <p><!-- 数量 --></p>
                    {% for order_goods in order.ordergoodsmodel_set.all %}
                        <!--展示商品的名称-->
                        {{ order_goods.goods.productname }}
                        <li>
                            <img src="{{ order_goods.goods.productimg }}" alt="">
                        </li>
                        <!--处理结束-->
                    {% endfor %}
                </a>
            </li>
        <!--订单处理结束-->
    {% endfor %}

    </ul>


{% endblock %}

axf1/templates/order/order_list_wait_pay.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待付款订单列表</h3>
    {% for order in orders %}
    <ul>
        <!--订单信息展示-->
            <li>
                <a href="">
                    <p><!-- 订单id -->订单编号: {{ order.o_num }}</p>
                    <p><!-- 数量 --></p>
                    {% for order_goods in order.ordergoodsmodel_set.all %}
                        <!--展示商品的名称-->商品名:
                        {{ order_goods.goods.productname }}
                        <li>
                            <a href="{% url 'app1:pay_my_goods' %}?order_id={{ order.id }}">
                            <img src="{{ order_goods.goods.productimg }}" alt="">
                            </a>
                        </li>
                        <!--处理结束-->
                    {% endfor %}
                </a>
            </li>
        <!--订单处理结束-->
    {% endfor %}

    </ul>


{% endblock %}