axf1/app1/urls.py
from django.conf.urls import url
from app1 import views

urlpatterns = [
    # 首页
    url(r'^home/', views.home, name='home'),
    # 购物车
    url(r'^cart/', views.cart, name='cart'),
    # 闪购超市
    url(r'^market/$', views.market, name='market'),
    url(r'^market/(\d+)/(\d+)/(\d+)', views.use_market, name='use_market'),
    # 个人中心
    url(r'^mine/', views.mine, name='mine'),

    # 添加购物车
    url(r'^addCart/', views.add_cart, name='addCart'),
    url(r'^subCart/', views.sub_cart, name='subCart'),

    # 修改购物车中商品的选择情况
    url(r'^changeSelectStatus/', views.change_select_status, name='change'),

    # 下单
    url(r'^g_order/', views.g_order, name='g_order'),

    # 修改名单状态
    url(r'^changeOrderStatus/', views.change_order_status, name='change_order_status'),

    # 待付款订单
    url(r'^waitPay/', views.order_wait_pay, name='order_wait_pay'),

    # 付款页面
    url(r'^payMygoods/', views.pay_my_goods, name='pay_my_goods'),

    # 待收货
    url(r'^payed/', views.order_payed, name='order_payed'),

    # 总价
    url(r'^allPrice/', views.all_price, name='all_price'),

    # 全选
    url(r'^changeAll/', views.change_all, name='change_all')

]

axf1/axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.views.static import serve

from app1 import views
from axf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app1/', include('app1.urls', namespace='app1')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^$', views.home),
    # 部署时用到的路由
    url(r'^static(?P<path>.*)$', serve, {"document_root": settings.STATICFILES_DIRS[0]}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

axf1/templates/cart/cart.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'app/cart/cart.css' %}">
{% endblock %}

{% block EXTJS %}
    {{ block.super }}
{#    <script type="text/javascript" src="{% static 'app/cart/js/cart.js' %}"></script>#}
    <script type="text/javascript" src="{% static 'app/common/function.js' %}"></script>
{% endblock %}


{% block content %}

    <div id="cart">

        <h3>购物车</h3>

        <div class="full">

            <section class="clear">

                <ul>
                    <li>收货人:王帅帅<div><p><span><a href="#">修改&gt;</a></span></p></div></li>
                    <li>电话:8008208820 </li>
                    <li>收货地址:宝胜北里西区28号天丰利商城</li>

                </ul>


                <div class="bill">

                    <p>闪送超市</p>

                    <a href="#">凑单专区</a>

                    <p>满100减99</p>

                </div>

                <p class="delivery">

                    <span>收货时间:</span>
                    <span>一小时送达</span>
                    <a href="#">可送达&gt;</a>
                </p>

                <p class="delivery">
                    <span>留言:</span>
                    <input type="text" placeholder="有什么特殊需求">
                </p>


                <menu>

                    <ul>
                        <!--购物车信息展示-->
                        {% csrf_token %}

                           {% for cart in user_carts %}
                            <div  id="goods_id_{{ cart.goods.id }}">
                            <li class="menuList">
                                <div class="confirm">
                                    <span>
                                        {% if cart.is_select == 1 %}
                                            <span id="cart_id_{{ cart.id }}" onclick="changeSelectStatus({{ cart.id }})">√</span>
                                        {% else %}
                                            <span id="cart_id_{{ cart.id }}" onclick="changeSelectStatus({{ cart.id }})">×</span>
                                        {% endif %}

                                    </span>
                                </div>
                                <a href="#">
                                    <img src="{{ cart.goods.productimg }}" alt="">
                                    <p>{{ cart.goods.productlongname }}</p>
                                    <p style="color: red;">&nbsp;&nbsp;&nbsp;￥{{ cart.goods.price }}</p>
                                </a>
                                <section>
                                    <button onclick="subCart({{ cart.goods.id }})">-</button>
                                    <span id="num_{{ cart.goods.id }}">{{ cart.c_num }}</span>
                                    <button onclick="addCart({{ cart.goods.id }})">+</button>
                                </section>
                            </li>
                            </div>
                            {% endfor %}
                        <!--购物车数据处理结束-->


                        <li class="payTheBill">

                            <div class="confirm">
                                <span>

                                        <span>√</span>

                                        <span>×</span>

                                </span>
                            </div>

                            <p>
                                <span onclick="checkAll()">全选</span>
                                <span id="allPrice"></span>
                            </p>

                            <span><a href="{% url 'app1:g_order' %}">下单</a></span>
                            <span>{{ msg }}</span>

                        </li>

                    </ul>

                </menu>

{#            <div class="menuList">#}
{##}
{#                {% for cart in carts %}#}
{##}
{#                    <div class="confirm">#}
{#                    <span>#}
{#                        <span>√</span>#}
{#                    </span>#}
{#                    </div>#}
{##}
{#                    <a href="#">#}
{#                        <img src="{{ cart.goods.productimg }}" alt="{{ cart.goods.productlongname }}">#}
{#                        <p>{{ cart.goods.productlongname }}</p>#}
{#                    </a>#}
{##}
{#                {% endfor %}#}
{##}
{##}
{#            </div>#}
            </section>



        </div>


    </div>


{% endblock %}